#!/bin/bash

# Fix Payment Instrument Issue for AWS Bedrock Marketplace Models
# Error: INVALID_PAYMENT_INSTRUMENT - A valid payment instrument must be provided

set -e

echo "💳 AWS Bedrock Payment Setup Guide"
echo "════════════════════════════════════════════════════════════════"
echo ""
echo "❌ Current Error:"
echo "   Model access is denied due to INVALID_PAYMENT_INSTRUMENT"
echo ""
echo "✅ What This Means:"
echo "   • Your Claude Haiku 4.5 marketplace agreement IS approved ✓"
echo "   • But your AWS account needs a valid payment method"
echo ""
echo "🔧 How to Fix (2-3 minutes):"
echo ""
echo "1️⃣  Add Payment Method to AWS Account:"
echo "   • Go to: https://console.aws.amazon.com/billing/home#/paymentmethods"
echo "   • Click 'Add payment method'"
echo "   • Enter valid credit/debit card"
echo "   • Click 'Verify and add'"
echo ""
echo "2️⃣  Verify Marketplace Subscription:"
echo "   • Go to: https://console.aws.amazon.com/marketplace/home#/subscriptions"
echo "   • Look for 'Claude Haiku 4.5' subscription"
echo "   • Status should show 'Active' or 'Pending'"
echo ""
echo "3️⃣  Wait 2 Minutes & Test Again:"
echo "   • Payment method propagation takes 1-2 minutes"
echo "   • Run: ./scripts/test-global-profile.sh"
echo ""
echo "💰 Pricing Info:"
echo "   Claude Haiku 4.5 (Global Profile):"
echo "   • Input: \$0.001 per 1K tokens (~10% cheaper than US profile)"
echo "   • Output: \$0.005 per 1K tokens"
echo "   • For 300-team hackathon: ~\$488/day savings vs OpenAI"
echo ""
echo "🆘 Still Having Issues?"
echo "   • Check AWS account is not in suspended state"
echo "   • Verify region is us-east-1"
echo "   • Contact AWS Support: https://console.aws.amazon.com/support"
echo ""
echo "📚 Quick Links:"
echo "   • Payment Methods: https://console.aws.amazon.com/billing/home#/paymentmethods"
echo "   • Subscriptions:   https://console.aws.amazon.com/marketplace/home#/subscriptions"
echo "   • Account Status:  https://console.aws.amazon.com/billing/home#/account"
echo ""
