#!/bin/bash

# Fix Marketplace Subscription for Claude Haiku 4.5
# The marketplace subscription needs explicit completion even if payment is configured

set -e

echo "🔧 AWS Marketplace Subscription Fix Guide"
echo "═══════════════════════════════════════════════════════════"
echo ""
echo "📋 Current Status:"
echo "   ✅ AWS account billing: Working"
echo "   ✅ Payment method: Configured"  
echo "   ✅ Model availability: Claude Haiku 4.5 is ACTIVE"
echo "   ❌ Marketplace subscription: INCOMPLETE"
echo ""
echo "🎯 The Issue:"
echo "   Your marketplace agreement was accepted, but the subscription"
echo "   needs to be explicitly completed for billing to work."
echo ""
echo "🔧 EXACT Steps to Fix:"
echo ""
echo "1️⃣  Visit Bedrock Model Access Console:"
echo "   → Open: https://us-east-1.console.aws.amazon.com/bedrock/home?region=us-east-1#/modelaccess"
echo ""
echo "2️⃣  Check Claude Haiku 4.5 Status:"
echo "   → Look for 'Claude Haiku 4.5' in the list"
echo "   → If status shows 'Available' or 'Access granted' - SKIP to step 4"
echo "   → If status shows anything else - continue to step 3"
echo ""
echo "3️⃣  Request Model Access (if needed):"
echo "   → Click 'Edit' (top right)"
echo "   → Find 'Anthropic' section"
echo "   → Check the box for 'Claude Haiku 4.5'"
echo "   → Click 'Save changes'"
echo "   → Review marketplace terms"
echo "   → Click 'Subscribe' to complete subscription"
echo ""
echo "4️⃣  Complete AWS Marketplace Subscription:"
echo "   → Open: https://console.aws.amazon.com/marketplace/home#/subscriptions"
echo "   → Look for 'Claude Haiku 4.5' or 'Anthropic Claude' subscription"
echo "   → If status is 'Pending' or 'Action Required':"
echo "     • Click on the subscription"
echo "     • Complete any required steps"
echo "     • Confirm payment authorization"
echo ""
echo "5️⃣  Alternative: Re-subscribe via Marketplace:"
echo "   → Open: https://aws.amazon.com/marketplace/pp/prodview-ixhq6qtvuazoc"
echo "   → Click 'Continue to Subscribe'"
echo "   → Review pricing: \$0.001 per 1K input tokens"
echo "   → Click 'Subscribe'"
echo "   → Wait for 'Subscription successful' message"
echo ""
echo "6️⃣  Wait & Verify:"
echo "   → Wait 2-3 minutes after completing subscription"
echo "   → Run: cd /Users/suhaib/Downloads/Development/Util/visionx-eval && scripts/test-global-profile.sh"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "💡 Common Issues:"
echo ""
echo "   • 'No payment method' - Add card at:"
echo "     https://console.aws.amazon.com/billing/home#/paymentmethods"
echo ""
echo "   • 'Marketplace subscription pending' - Check:"
echo "     https://console.aws.amazon.com/marketplace/home#/subscriptions"
echo ""
echo "   • 'Use case not submitted' - Go to model access and enable model"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "🆘 If Still Not Working:"
echo ""
echo "   Try the US Regional Profile instead (doesn't always need marketplace):"
echo "   Edit: apps/worker/.env.aws"
echo "   Change to: AWS_BEDROCK_MODEL_ID=arn:aws:bedrock:us-east-1:668226797980:inference-profile/us.anthropic.claude-haiku-4-5-20251001-v1:0"
echo ""
echo "   Or use older Claude 3 Haiku (no marketplace needed):"
echo "   Change to: AWS_BEDROCK_MODEL_ID=anthropic.claude-3-haiku-20240307-v1:0"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "📚 Quick Access Links:"
echo "   • Model Access:  https://us-east-1.console.aws.amazon.com/bedrock/home?region=us-east-1#/modelaccess"
echo "   • Subscriptions: https://console.aws.amazon.com/marketplace/home#/subscriptions"
echo "   • Billing:       https://console.aws.amazon.com/billing/home#/paymentmethods"
echo "   • Account:       https://console.aws.amazon.com/billing/home#/account"
echo ""
